--USE MOVIES



--SELECT NAME
--FROM STARSIN JOIN MOVIESTAR ON NAME = STARNAME
--WHERE MOVIETITLE = 'Terms of Endearment' AND GENDER = 'M';

--SELECT STARNAME
--FROM MOVIE JOIN STARSIN ON YEAR = MOVIEYEAR
--WHERE STUDIONAME = 'MGM' AND YEAR = 1995;

--SELECT DISTINCT NAME
--FROM MOVIE JOIN MOVIEEXEC ON CERT# = PRODUCERC#
--WHERE STUDIONAME = 'MGM';

--SELECT MS1.TITLE
--FROM MOVIE MS1, MOVIE MS2
--WHERE MS2.TITLE = 'STAR WARS' AND MS2.LENGTH < MS1.LENGTH ;

--5--
--SELECT DISTINCT M2.NAME
--FROM MOVIEEXEC M1, MOVIEEXEC M2 JOIN MOVIE ON CERT# = PRODUCERC#
--WHERE M1.NAME = 'Merv Griffin' AND M1.NETWORTH < M2.NETWORTH

--6--
--SELECT MOVIE.TITLE
--FROM MOVIEEXEC M1, MOVIEEXEC M2 JOIN MOVIE ON CERT# = PRODUCERC#
--WHERE M1.NAME = 'Merv Griffin' AND M1.NETWORTH < M2.NETWORTH;



--USE PC


--1--
--SELECT P.MAKER, L.speed
--FROM PRODUCT P JOIN LAPTOP L
--ON P.MODEL = L.MODEL
--WHERE L.HD > 9;


--2--
--SELECT DISTINCT P.MODEL, PT.PRICE
--FROM PRODUCT P JOIN (SELECT MODEL, PRICE FROM PC
--					UNION ALL
--					SELECT MODEL, PRICE FROM LAPTOP
--					UNION ALL
--					SELECT MODEL, PRICE FROM PRINTER) PT
--ON P.MODEL = PT.MODEL
--WHERE P.MAKER = 'B';

--3--
--SELECT DISTINCT C1.HD
--FROM PC C1, PC C2
--WHERE C1.CODE <> C2.CODE AND C1.HD = C2.HD;


--4--
--SELECT C1.MODEL, C2.MODEL
--FROM PC C1, PC C2
--WHERE C1.MODEL <> C2.MODEL AND C1.SPEED = C2.SPEED AND C1.RAM = C2.RAM AND C1.MODEL < C2.MODEL


----SELECT P.MAKER
----FROM PC C2 JOIN PRODUCT P
----ON P.MODEL = C2.MODEL
----WHERE C2.PRICE > 400;


USE SHIPS

--1--
--SELECT S.NAME
--FROM CLASSES C JOIN SHIPS S
--ON C.CLASS = S.CLASS
--WHERE C.DISPLACEMENT > 50000;


--3--
--SELECT DISTINCT C2.COUNTRY
--FROM CLASSES C1, CLASSES C2 
--WHERE C1.TYPE = 'bb' AND C2.TYPE = 'bc';

--SELECT O1.SHIP
--FROM OUTCOMES O1
--WHERE O1.RESULT = 'DAMAGED';


