--USE PC

--SELECT AVG(SPEED) as AvgSpeed
--FROM PC

--SELECT P.MAKER, AVG(SCREEN) as AvgScreen
--FROM LAPTOP L JOIN PRODUCT P
--ON L.model = P.model
--GROUP BY P.MAKER

--SELECT AVG(SPEED) AS AvgSpeed
--FROM LAPTOP L
--WHERE L.PRICE > 1000;


--SELECT P.MAKER, AVG(PRICE) AS AvgPrice
--FROM PC C JOIN PRODUCT P
--ON C.MODEL = P.MODEL
--WHERE P.MAKER = 'A'
--GROUP BY P.MAKER;


--SELECT P.MAKER, AVG(PT.PRICE) AS AvgPrice
--FROM PRODUCT P JOIN (SELECT MODEL, PRICE FROM PC
--					UNION ALL
--					SELECT MODEL, PRICE FROM LAPTOP) PT
--ON P.MODEL = PT.MODEL
--WHERE P.MAKER = 'B'
--GROUP BY P.MAKER;




--SELECT P.MAKER, AVG(L.PRICE) AS AvgPrice
--FROM LAPTOP L JOIN PRODUCT P
--ON L.MODEL = P.MODEL
--WHERE P.MAKER = 'B'
--GROUP BY P.MAKER;


--SELECT C.SPEED, AVG(C.PRICE) AS AvgPrice
--FROM PC C
--GROUP BY C.SPEED;


--SELECT P.MAKER, COUNT(*) AS CNT
--FROM PC C JOIN PRODUCT P
--ON C.MODEL = P.MODEL

--GROUP BY P.MAKER
--HAVING COUNT(*) >= 3;


--SELECT P.MAKER, MAX(C.PRICE) AS MaxPrice
--FROM PC C JOIN PRODUCT P
--ON C.MODEL = P.MODEL
--GROUP BY P.MAKER
--HAVING MAX(C.PRICE) >= ALL(SELECT PRICE
--							FROM PC);


--SELECT Speed, AVG(PRICE) AS AvgPrice
--FROM PC C
--WHERE SPEED > 800
--GROUP BY SPEED;



--SELECT AVG(C.HD) AS AvgHDD
--FROM PC C JOIN PRODUCT P
--ON C.MODEL = P.MODEL
--WHERE P.MAKER IN (SELECT MAKER
--					FROM PRODUCT
--					WHERE TYPE='PRINTER');





					









