USE ships

--1task--
--SELECT COUNT(CLASS) classNum
--FROM CLASSES C

--2task--
--SELECT C.CLASS, AVG(NUMGUNS) avgGuns
--FROM CLASSES C
--GROUP BY C.CLASS

--3task--
--SELECT AVG(NUMGUNS) avgGuns
--FROM CLASSES C

--4task--
--SELECT C.CLASS, MIN(S.LAUNCHED) FirstYear, MAX(S.LAUNCHED) LastYear
--FROM CLASSES C JOIN SHIPS S
--ON C.CLASS = S.CLASS
--GROUP BY C.CLASS

--5task--
--SELECT S.CLASS, COUNT (OUT.RESULT) "Number of sunk ships"
--FROM SHIPS S JOIN OUTCOMES OUT
--ON S.NAME = OUT.SHIP
--WHERE OUT.RESULT = 'sunk'
--GROUP BY S.CLASS;


--6task--
--SELECT S.CLASS, COUNT (OUT.RESULT) "Number of sunk ships"
--FROM SHIPS S JOIN OUTCOMES OUT
--ON S.NAME = OUT.SHIP
--WHERE OUT.RESULT = 'sunk'
--GROUP BY S.CLASS
--HAVING COUNT(OUT.RESULT) >= 2;

--7task--
--SELECT C.COUNTRY, AVG(BORE) avg_bore
--FROM CLASSES C
--GROUP BY C.COUNTRY




