USE Movies;
--SELECT ADDRESS
--FROM STUDIO
--WHERE NAME = 'MGM';
 

 --SELECT BIRTHDATE
 --FROM MOVIESTAR
 --WHERE NAME = 'Sandra Bullock'

 --SELECT STARNAME
 --FROM STARSIN
 --WHERE MOVIEYEAR = 1980 and MOVIETITLE LIKE '%Empire%'

 --SELECT NAME
 --FROM MOVIEEXEC
 --WHERE NETWORTH >= 10000000

 --SELECT NAME
 --FROM MOVIESTAR
 --WHERE GENDER = 'M' or ADDRESS = 'Prefect Rd.'


USE PC;
--SELECT MODEL, SPEED MHZ, HD GB 
--FROM PC
-- WHERE PRICE < 1200;

--SELECT DISTINCT MAKER
--FROM PRODUCT
--WHERE TYPE = 'PRINTER'

--SELECT MODEL, RAM, SCREEN
--FROM LAPTOP
--WHERE PRICE > 1000

--SELECT *
--FROM PRINTER
--WHERE COLOR = 'Y'

--SELECT MODEL, SPEED, HD
--FROM PC
--WHERE CD in ('12x', '16x') AND PRICE < 2000



USE SHIPS;
--SELECT CLASS, COUNTRY
--FROM CLASSES
--WHERE NUMGUNS < 10;

--SELECT NAME AS shipName
--FROM SHIPS
--WHERE LAUNCHED < 1918

--SELECT SHIP, BATTLE
--FROM OUTCOMES
--WHERE RESULT = 'sunk'

--SELECT NAME
--FROM SHIPS
--WHERE NAME = CLASS

--SELECT NAME
--FROM SHIPS
--WHERE NAME LIKE 'R%'