--USE MOVIES

--1-- 
--SELECT S.NAME, S.ADDRESS, M.TITLE, M.LENGTH 
--FROM STUDIO S JOIN MOVIE M
--ON S.NAME = M.STUDIONAME
--WHERE M.YEAR > 1980 AND S.NAME LIKE 'M%';


--2--
--SELECT M.NAME, M.ADDRESS, S.MOVIETITLE
--FROM STARSIN S JOIN MOVIESTAR M
--ON S.STARNAME = M.NAME
--WHERE M.NAME LIKE 'J%' AND S.MOVIEYEAR > 1990;


--3--
--SELECT M.TITLE, M.YEAR, M.LENGTH
--FROM MOVIE M
--WHERE M.LENGTH > 120 OR M.LENGTH IS NULL AND M.YEAR < 2000;


--4--
--SELECT M.NAME, M.GENDER
--FROM MOVIESTAR M
--WHERE M.NAME LIKE 'J%' AND M.BIRTHDATE > 1948
--ORDER BY M.NAME DESC;


--5--
--SELECT M.STUDIONAME, COUNT(S.STARNAME)
--FROM MOVIE M JOIN STARSIN S
--ON M.TITLE = S.MOVIETITLE
--GROUP BY M.STUDIONAME


--6--
--SELECT M.NAME, COUNT(S.MOVIETITLE)
--FROM STARSIN S JOIN MOVIESTAR M
--ON S.STARNAME = M.NAME
--GROUP BY M.NAME

--SELECT S.STARNAME, COUNT(S.MOVIETITLE)
--FROM STARSIN S
--GROUP BY S.STARNAME


--7--
--SELECT M.STUDIONAME, M.TITLE, M.YEAR
--FROM MOVIE M 
--WHERE M.YEAR >= ALL (SELECT YEAR
--					FROM MOVIE
--					WHERE M.STUDIONAME = STUDIONAME)


--8--
--SELECT M.NAME
--FROM MOVIESTAR M
--WHERE  M.GENDER = 'M' AND M.BIRTHDATE >= ALL (SELECT BIRTHDATE
--						FROM MOVIESTAR
--						WHERE GENDER = 'M')


--9--
--SELECT M.STUDIONAME, S.STARNAME, COUNT(S.MOVIETITLE) CNT
--FROM MOVIE M JOIN STARSIN S
--ON M.TITLE = S.MOVIETITLE
--GROUP BY M.STUDIONAME, S.STARNAME


--10--
--SELECT S.STARNAME, ME.NAME
--FROM MOVIEEXEC ME JOIN MOVIE M
--ON ME.CERT# = M.PRODUCERC#
--JOIN STARSIN S
--ON M.TITLE = S.MOVIETITLE
--WHERE ME.NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC);


--11--
--SELECT S.MOVIETITLE, S.MOVIEYEAR, COUNT(STARNAME)
--FROM STARSIN S
--GROUP BY S.MOVIETITLE, S.MOVIEYEAR
--HAVING COUNT(STARNAME) > 2;


--USE SHIPS

--1--
--SELECT DISTINCT S.NAME
--FROM SHIPS S JOIN OUTCOMES T
--ON S.NAME = T.SHIP
--WHERE S.NAME LIKE 'C%' OR S.NAME LIKE 'K%';


--2--
--SELECT DISTINCT S.NAME, C.COUNTRY
--FROM CLASSES C JOIN SHIPS S
--ON C.CLASS = S.CLASS
--LEFT JOIN OUTCOMES T
--ON S.NAME = T.SHIP
--WHERE T.RESULT <> 'SUNK' OR S.NAME NOT IN (SELECT SHIP FROM OUTCOMES);


--3--
--SELECT C.COUNTRY, COUNT(T.RESULT) Sunk
--FROM CLASSES C LEFT JOIN SHIPS S
--ON C.CLASS = S.CLASS
--LEFT JOIN OUTCOMES T
--ON S.NAME = T.SHIP
--WHERE T.RESULT = 'SUNK' OR S.NAME NOT IN (SELECT SHIP FROM OUTCOMES)
--OR C.CLASS NOT IN (SELECT CLASS FROM SHIPS)
--GROUP BY C.COUNTRY


USE PC

--1--
--SELECT L.MODEL, L.CODE, L.SCREEN
--FROM LAPTOP L
--WHERE L.SCREEN = 15 OR L.SCREEN = 11;


--2--
--SELECT DISTINCT C.MODEL
--FROM PC C JOIN PRODUCT P
--ON C.MODEL = P.MODEL
--WHERE C.PRICE < (SELECT MIN(PRICE)
--				FROM LAPTOP L JOIN PRODUCT P1
--				ON L.MODEL = P1.MODEL
--				WHERE P.MAKER = P1.MAKER);


--3--
SELECT C.CODE, P.MAKER, COUNT(C.MODEL)
FROM PRODUCT P JOIN PC C
ON P.MODEL = C.MODEL
GROUP BY C.CODE, P.MAKER










