USE MOVIES;
--SELECT STARNAME
--FROM MOVIESTAR JOIN STARSIN ON NAME = STARNAME
--WHERE MOVIETITLE = 'Terms of Endearment' AND GENDER = 'M';

--SELECT STARNAME
--FROM MOVIE JOIN STARSIN ON TITLE = MOVIETITLE
--WHERE YEAR = 1995 AND STUDIONAME = 'MGM';

--SELECT DISTINCT NAME
--FROM MOVIEEXEC JOIN MOVIE ON CERT# = PRODUCERC#
--WHERE STUDIONAME = 'MGM';

--SELECT ms1.title
--FROM MOVIE MS1, MOVIE MS2
--WHERE MS2.TITLE = 'Star Wars' AND MS2.LENGTH < MS1.LENGTH 

--SELECT MX2.NAME
--FROM MOVIEEXEC MX1, MOVIEEXEC MX2
--WHERE MX1.NAME = 'Merv Griffin' AND	MX1.NETWORTH < MX2.NETWORTH

--SELECT MOVIE.TITLE
--FROM MOVIEEXEC MX1, MOVIEEXEC MX2 JOIN MOVIE ON CERT# = PRODUCERC#
--WHERE MX1.NAME = 'Merv Griffin' AND	MX1.NETWORTH < MX2.NETWORTH




USE PC;

--SELECT MAKER, SPEED
--FROM PRODUCT JOIN LAPTOP ON PRODUCT.MODEL = LAPTOP.MODEL
--WHERE HD > 9;

--SELECT PRODUCT.MODEL, PRICE
--FROM PRODUCT JOIN LAPTOP ON PRODUCT.MODEL = LAPTOP.MODEL
--WHERE MAKER = 'B';
