use movies;
GO

CREATE VIEW RichExec11 
			(NAME, ADDRESS, CERT#)
AS
	SELECT NAME, ADDRESS, CERT#
	FROM MOVIEEXEC
	WHERE NETWORTH > 150000000;

INSERT INTO MOVIEEXEC(CERT#, NAME, ADDRESS, NETWORTH)
VALUES ('666', 'Jack Nicholson', 'Washington street', 400000000);

CREATE VIEW ExecutiveStar
			(NAME, ADDRESS, GENDER, BIRTHDATE, CERT#, NETWORTH)
AS
	SELECT ms.NAME, ms.ADDRESS, ms.GENDER, ms.BIRTHDATE, me.CERT#, me.NETWORTH
	FROM MOVIESTAR ms, MOVIEEXEC me
	WHERE ms.NAME = me.NAME


INSERT INTO MOVIEEXEC(CERT#, NAME, ADDRESS, NETWORTH)
VALUES ('444', 'Sandra Bullock', 'cool str', 500000000);

SELECT NAME
FROM ExecutiveStar
WHERE GENDER='F';


DROP VIEW ExecutiveStar
DROP VIEW RichExec11



use pc;
GO

CREATE INDEX product_maker1
ON Product(maker, model, type);
